# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 12 Oct 2017 09:13:38 +0000
*               @ALL          0
*               @user         8
