<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: dyb
 * Date: Sat, 14 Oct 2017 05:29:35 +0000
 */

$conf['title'] = 'oneplay';
$conf['lang'] = 'zh';
$conf['template'] = 'tpl_bootstrap';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['tpl_bootstrap']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['tpl_bootstrap']['bootswatchTheme'] = 'slate';
$conf['tpl']['tpl_bootstrap']['showThemeSwitcher'] = 1;
$conf['tpl']['tpl_bootstrap']['sidebarShowPageTitle'] = 0;
$conf['tpl']['tpl_bootstrap']['showUserHomeLink'] = 0;
$conf['tpl']['tpl_bootstrap']['individualTools'] = 1;
$conf['tpl']['tpl_bootstrap']['showIndividualTool'] = 'site,page';
$conf['tpl']['tpl_bootstrap']['showSearchButton'] = 0;
$conf['tpl']['tpl_bootstrap']['useLegacyNavbar'] = 1;
$conf['tpl']['tpl_bootstrap']['schemaOrgType'] = 'TechArticle';
$conf['tpl']['tpl_bootstrap']['pageOnPanel'] = 0;
$conf['tpl']['tpl_bootstrap']['tableStyle'] = 'striped,bordered,hover,condensed,responsive';
$conf['tpl']['tpl_bootstrap']['showLandingPage'] = 1;
$conf['tpl']['tpl_bootstrap']['showBadges'] = 0;
$conf['tpl']['tpl_bootstrap']['tocCollapseSubSections'] = 0;
$conf['tpl']['tpl_bootstrap']['tocPosition'] = 'left';
$conf['tpl']['tpl_bootstrap']['tocCollapseOnScroll'] = 0;
$conf['tpl']['tpl_bootstrap']['browserTitleCharSepNS'] = '/';
$conf['tpl']['tpl_bootstrap']['pageInfo'] = 'filename,date,editor,locked';
$conf['tpl']['tpl_bootstrap']['pageInfoDateFormat'] = 'human';
$conf['tpl']['tpl_bootstrap']['showPageIcons'] = 1;
$conf['tpl']['tpl_bootstrap']['pageIcons'] = 'print';
$conf['tpl']['tpl_bootstrap']['socialShareProviders'] = '';

// end auto-generated content
